### ISSUE TITLE
Only email or text in <author> ? 

### ISSUE THREAD

**Issue by samtsai15** [bcomnes/jsonfeed-to-rss#19]
Like this : 

`<author>samtsai15@gmail.com</author>`

or

`<author>samtsai15</author>`

**Comment by bcomnes** [comment]
The `author` field is an item level property but its not recommended by the RSS spec:

> 4.1.1.20.1 author
>
> Requirements
>
> An item's author element provides the e-mail address of the person who wrote the item (OPTIONAL).
>
> <author>jbb@dallas.example.com (Joe Bob Briggs)</author>
> 
> Recommendations
>
> A feed published by an individual SHOULD omit this element and use the managingEditor or webMaster channel elements to provide contact information.
> -- https://www.rssboard.org/rss-profile#element-channel-item-author

The `managingEditor`  and `webMaster` options are available to populate those fields.  Additionally iTunes supports an email address field separate from these, though you may use a variable to tie them all together. 

Closing please re-open if there are more issues or create a new one.
