### ISSUE TITLE
Category field under Item not rendering

### ISSUE THREAD

**Issue by dsmikeyorke** [bcomnes/jsonfeed-to-rss#61]
First off, thanks for creating this package! We're working with a client that could greatly benefit from the `<category>` field under `<item>`.  It looks like this is part of the [RSS 2.0 spec](https://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt) but when I try adding `category` it does not render in the feed.  Any recommendation on how to add this OR have the option to setup custom fields under `<item>`?

**Comment by bcomnes** [comment]
jsonfeed doesn't have a category field, but does have a tags array.  I believe I mapped the item tags array to rss categories. 

https://github.com/bcomnes/jsonfeed-to-rss/blob/master/jsonfeed-to-rss-object.js#L129

**Comment by dsmikeyorke** [comment]
@bcomnes Thanks for the quick response!  Adding `tags` instead of `category` did the trick.
