### ISSUE TITLE
Output contains debug statement

### ISSUE THREAD

**Issue by BeeFox-sys** [bcomnes/jsonfeed-to-rss#90]
When geneating rss, the ouput contains `console.log(&amp;quot;foo&amp;quot;)` in the channel description, instead of described channel description, this is likely a bug

**Comment by bcomnes** [comment]
Do you have an example that can reproduce this? I have not seen this before.

**Comment by BeeFox-sys** [comment]
nevermind, i just don't understand rss. i was thinking that the html would be stored in description, it is not :p

**Comment by bcomnes** [comment]
Sounds good.
